/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ezTrace.HadoopTrace */

#ifndef _Included_HadoopTrace
#define _Included_HadoopTrace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ezTrace.HadoopTrace
 * Method:    mapProlog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HadoopTrace_mapProlog
        (JNIEnv *, jobject);

/*
 * Class:     ezTrace.HadoopTrace
 * Method:    mapEpilog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HadoopTrace_mapEpilog
        (JNIEnv *, jobject);

/*
 * Class:     ezTrace.HadoopTrace
 * Method:    reduceProlog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HadoopTrace_reduceProlog
        (JNIEnv *, jobject);

/*
 * Class:     ezTrace.HadoopTrace
 * Method:    reduceEpilog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HadoopTrace_reduceEpilog
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
