#ifndef HADOOP_AGENT_HADOOPTRACE_EV_CODES_H
#define HADOOP_AGENT_HADOOPTRACE_EV_CODES_H

/*
 * This file defines the event codes that are used by the hadooptrace module.
 */

#include "ev_codes.h"

#define EZTRACE_HADOOP_EVENT_ID     USER_MODULE_ID(0x20)
#define EZTRACE_HADOOP_PREFIX       (EZTRACE_HADOOP_EVENT_ID << 8)

#define EZTRACE_HADOOP_MAP_PROLOG       (EZTRACE_HADOOP_PREFIX | 0x0001)
#define EZTRACE_HADOOP_MAP_EPILOG       (EZTRACE_HADOOP_PREFIX | 0x0002)

#define EZTRACE_HADOOP_REDUCE_PROLOG    (EZTRACE_HADOOP_PREFIX | 0x0011)
#define EZTRACE_HADOOP_REDUCE_EPILOG    (EZTRACE_HADOOP_PREFIX | 0x0012)

#endif //HADOOP_AGENT_HADOOPTRACE_EV_CODES_H
