/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hellothread_HelloThread */

#ifndef _Included_hellothread_HelloThread
#define _Included_hellothread_HelloThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hellothread_HelloThread
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hellothread_HelloThread_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
