/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_HelloWorld */

#ifndef _Included_hello_HelloWorld
#define _Included_hello_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_HelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
